(function(){
'use strict';
if(window.__tfV113)return;window.__tfV113=true;
const CODE='MEJORAR',CFG='taskflow_forced_routines_v113',META='taskflow_routines_v113_meta';
const MAIN='taskflow_db_v26',BACK='taskflow_db_v26_backup',REC='taskflow_db_v26_recovery',TOUCH='taskflow_cloud_local_touch_v1';
const PROJECT='taskflow-b0ece',API='https://firestore.googleapis.com/v1/projects/'+PROJECT+'/databases/(default)/documents';
const ROUTINES=[
 {id:'sung',name:'Sung Jin-Woo',needle:'SUNG JIN-WOO'},
 {id:'juridico',name:'Dominio Jurídico',needle:'DOMINIO JURIDICO'},
 {id:'mentalista',name:'Mentalista',needle:'MENTALISTA'}
];
let refreshTimer=0,cloudUid='',cloudTimer=0,cloudBusy=false;
const $=id=>document.getElementById(id);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
function get(k){try{return localStorage.getItem(k)}catch(_){return null}}
function set(k,v){try{localStorage.setItem(k,String(v));return true}catch(_){return false}}
function json(k,f={}){try{const x=JSON.parse(get(k)||'null');return x&&typeof x==='object'?x:f}catch(_){return f}}
function cfg(){const s=json(CFG,{});let c=false;ROUTINES.forEach(r=>{if(typeof s[r.id]!=='boolean'){s[r.id]=false;c=true}});if(c)set(CFG,JSON.stringify(s));return s}
function saveCfg(s){set(CFG,JSON.stringify(s));markCloud();apply();renderManager()}

function style(){if($('tfV113Style'))return;const s=document.createElement('style');s.id='tfV113Style';s.textContent=`
#tfPairV113{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important;width:100%!important;align-items:stretch!important}#tfPairV113.tf-one{grid-template-columns:1fr!important}#tfPairV113>*{width:100%!important;max-width:none!important;min-width:0!important;grid-column:auto!important;margin:0!important}
.tf113-modal{position:fixed;inset:0;z-index:2147483200;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,16,.8);backdrop-filter:blur(8px)}.tf113-modal.open{display:flex}.tf113-box{width:min(500px,100%);max-height:82dvh;overflow:auto;border-radius:22px;border:1px solid rgba(78,205,196,.24);background:linear-gradient(160deg,#121b30,#090e1b);box-shadow:0 30px 90px rgba(0,0,0,.55);padding:18px;color:#fff}.tf113-head{display:flex;justify-content:space-between;gap:14px}.tf113-head small{color:#55e1d3;font-size:9px;font-weight:900;letter-spacing:.14em}.tf113-head h2{margin:5px 0;font-size:23px}.tf113-head p{margin:0;color:#93a1b7;font-size:12px;line-height:1.45}.tf113-x{width:40px;height:40px;flex:0 0 40px;border-radius:12px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#fff;font-size:25px}.tf113-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:15px 0 10px}.tf113-actions button,.tf113-done,.tf113-confirm{min-height:42px;border-radius:12px;border:1px solid rgba(78,205,196,.25);background:rgba(78,205,196,.09);color:#63eadc;font-weight:850}.tf113-actions button:last-child{color:#ff9da7;border-color:rgba(255,100,115,.22);background:rgba(255,90,105,.07)}.tf113-list{display:grid;gap:8px}.tf113-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.03)}.tf113-row strong{display:block;font-size:13px}.tf113-row small{display:block;margin-top:3px;color:#8491a7;font-size:9px}.tf113-row input{position:absolute;opacity:0}.tf113-sw{width:46px;height:26px;border-radius:99px;background:#263145;position:relative;flex:0 0 46px}.tf113-sw:after{content:"";position:absolute;width:20px;height:20px;left:3px;top:3px;border-radius:50%;background:#8b96a8;transition:.2s}.tf113-row input:checked+.tf113-sw{background:rgba(54,220,201,.36)}.tf113-row input:checked+.tf113-sw:after{left:23px;background:#51e3d4}.tf113-done,.tf113-confirm{width:100%;margin-top:12px}.tf113-warning{margin:13px 0;padding:12px;border-radius:13px;border:1px solid rgba(255,166,72,.20);background:rgba(255,140,52,.06);color:#b8c3d4;font-size:12px;line-height:1.5}.tf113-warning strong{color:#fff}.tf113-confirm{color:#ffc184;border-color:rgba(255,166,72,.28);background:rgba(255,140,52,.10)}#tfSystemResetV113{margin-top:8px!important;border-color:rgba(255,166,72,.28)!important;background:rgba(255,140,52,.08)!important;color:#ffb66f!important}@media(max-width:430px){#tfPairV113{gap:8px!important}.tf113-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function card(term){const t=norm(term);const els=[...document.querySelectorAll('button,[role="button"],article,.quick-action-btn,[class*="routine"],[class*="card"],[class*="tile"]')].filter(el=>!el.closest('.tf113-modal,#tfProfileOverlay')&&norm(el.textContent).includes(t)&&norm(el.textContent).length<600);els.sort((a,b)=>norm(a.textContent).length-norm(b.textContent).length);return els[0]||null}
function hideForense(){const m=card('MENTALISTA'),f=card('FORENSE');if(!f)return;if(m&&m===f){const w=document.createTreeWalker(f,NodeFilter.SHOW_TEXT);const a=[];let n;while((n=w.nextNode()))a.push(n);a.forEach(x=>{if(/forense/i.test(x.nodeValue||''))x.nodeValue=(x.nodeValue||'').replace(/\s*forense\s*/gi,' ').replace(/\s{2,}/g,' ').trim()})}else{f.style.display='none';f.setAttribute('aria-hidden','true');f.dataset.tf113Forense='1'}}
function show(cardEl,on,id){if(!cardEl)return;cardEl.dataset.tf113Routine=id;if(!on){if(cardEl.dataset.tf113Prev===undefined)cardEl.dataset.tf113Prev=cardEl.style.display||'';cardEl.style.display='none';cardEl.setAttribute('aria-hidden','true')}else{if(cardEl.dataset.tf113Prev!==undefined){cardEl.style.display=cardEl.dataset.tf113Prev;delete cardEl.dataset.tf113Prev}else if(cardEl.style.display==='none'&&!cardEl.dataset.tf113Forense)cardEl.style.display='';cardEl.removeAttribute('aria-hidden')}}
function pair(){const a=card('50/30/20'),b=card('MENTALISTA');if(!a)return;const active=b&&cfg().mentalista===true&&b.style.display!=='none';let p=$('tfPairV113');if(active&&a!==b){if(!p){p=document.createElement('div');p.id='tfPairV113';a.parentElement&&a.parentElement.insertBefore(p,a)}p.classList.remove('tf-one');if(a.parentElement!==p)p.appendChild(a);if(b.parentElement!==p)p.appendChild(b)}else if(p){p.classList.add('tf-one');if(a.parentElement!==p)p.appendChild(a)}}
function apply(){hideForense();const s=cfg();ROUTINES.forEach(r=>show(card(r.needle),s[r.id]===true,r.id));pair()}

function manager(){if($('tfManagerV113'))return;const o=document.createElement('div');o.id='tfManagerV113';o.className='tf113-modal';o.setAttribute('aria-hidden','true');o.innerHTML='<section class="tf113-box" role="dialog" aria-modal="true"><div class="tf113-head"><div><small>CONFIGURACIÓN DEL SISTEMA</small><h2>Rutinas predeterminadas</h2><p>Todas empiezan desactivadas. Activa únicamente las que quieras utilizar.</p></div><button class="tf113-x" type="button" data-close-manager>×</button></div><div class="tf113-actions"><button id="tf113AllOn" type="button">Activar todas</button><button id="tf113AllOff" type="button">Desactivar todas</button></div><div class="tf113-list" id="tf113List"></div><button class="tf113-done" type="button" data-close-manager>Guardar y cerrar</button></section>';document.body.appendChild(o);$('tf113AllOn').onclick=()=>{const s=cfg();ROUTINES.forEach(r=>s[r.id]=true);saveCfg(s)};$('tf113AllOff').onclick=()=>{const s=cfg();ROUTINES.forEach(r=>s[r.id]=false);saveCfg(s)};o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-close-manager]'))closeManager()});renderManager()}
function renderManager(){const l=$('tf113List');if(!l)return;const s=cfg();l.innerHTML='';ROUTINES.forEach(r=>{const x=document.createElement('label');x.className='tf113-row';x.innerHTML='<span><strong>'+r.name+'</strong><small>Rutina predeterminada del sistema</small></span><input type="checkbox" '+(s[r.id]?'checked':'')+'><i class="tf113-sw"></i>';x.querySelector('input').onchange=e=>{const n=cfg();n[r.id]=!!e.target.checked;saveCfg(n)};l.appendChild(x)})}
function openManager(){manager();renderManager();const o=$('tfManagerV113');o.classList.add('open');o.setAttribute('aria-hidden','false')}
function closeManager(){const o=$('tfManagerV113');if(o){o.classList.remove('open');o.setAttribute('aria-hidden','true')}}
function isSearch(el){return el&&el.tagName==='INPUT'&&(el.type==='search'||norm(el.placeholder).includes('BUSCAR'))}
function search(e){const el=e.target;if(!isSearch(el)||norm(el.value)!==CODE)return;e.preventDefault();e.stopImmediatePropagation();el.value='';try{el.dispatchEvent(new Event('input',{bubbles:true}))}catch(_){}setTimeout(openManager,0)}

function resetModal(){if($('tfResetModalV113'))return;const o=document.createElement('div');o.id='tfResetModalV113';o.className='tf113-modal';o.setAttribute('aria-hidden','true');o.innerHTML='<section class="tf113-box" role="dialog" aria-modal="true"><div class="tf113-head"><div><small>REINICIO DE SISTEMA</small><h2>Volver a 0 días</h2><p>Reinicia únicamente los días de progreso y fallas del sistema.</p></div><button class="tf113-x" type="button" data-close-reset>×</button></div><div class="tf113-warning"><strong>Tus hábitos y tareas NO se borrarán ni se reiniciarán.</strong><br>Para eliminar o editar hábitos y tareas debes hacerlo manualmente.</div><button class="tf113-confirm" id="tf113ConfirmReset" type="button">Confirmar reinicio a 0 días</button></section>';document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-close-reset]'))closeReset()});$('tf113ConfirmReset').onclick=resetProgress}
function mountReset(){if($('tfSystemResetV113'))return;const box=$('tfProfileUserBox');if(!box)return;const b=document.createElement('button');b.id='tfSystemResetV113';b.type='button';b.className='tf-profile-action';b.textContent='Reinicio de sistema';b.onclick=openReset;const sign=$('tfProfileSignOut');sign&&sign.parentElement===box?box.insertBefore(b,sign):box.appendChild(b)}
function openReset(){resetModal();const o=$('tfResetModalV113');o.classList.add('open');o.setAttribute('aria-hidden','false')}
function closeReset(){const o=$('tfResetModalV113');if(o){o.classList.remove('open');o.setAttribute('aria-hidden','true')}}
function protectedBranch(k){const n=norm(k).replace(/[^A-Z0-9]/g,'');return /^(TASKS?|TAREAS?|HABITS?|HABITOS?|AVITOS?)$/.test(n)}
function counterKey(k){const n=norm(k).replace(/[^A-Z0-9]/g,'');if(!n||/(DATE|FECHA|TIMESTAMP|SAVEDAT|UPDATEDAT|CREATEDAT|LASTRESET|NEXTRESET)/.test(n))return false;return /(STREAK|RACHA|CONSECUTIVE|CONSECUTIVOS|DAYS|DIAS)/.test(n)||/(FAIL|FAILURE|FALLA|MISSED).*(COUNT|COUNTER|TOTAL)$/.test(n)||/^(FAILS|FAILURES|FALLAS|DAYCOUNT|DIAS)$/.test(n)}
function walk(v,k){if(protectedBranch(k))return[v,0];let c=0;if(typeof v==='number'&&Number.isFinite(v)&&counterKey(k))return[0,v!==0?1:0];if(typeof v==='string'&&/^\d+(\.\d+)?$/.test(v)&&counterKey(k))return['0',v!=='0'?1:0];if(Array.isArray(v)){return[v.map((x,i)=>{if(x&&typeof x==='object'){const r=walk(x,String(i));c+=r[1];return r[0]}return x}),c]}if(v&&typeof v==='object'){const o={};Object.keys(v).forEach(x=>{const r=walk(v[x],x);o[x]=r[0];c+=r[1]});return[o,c]}return[v,0]}
function processKey(k){const raw=get(k);if(!raw)return 0;let d;try{d=JSON.parse(raw)}catch(_){return 0}if(!d||typeof d!=='object')return 0;const r=walk(d,k);if(r[1])set(k,JSON.stringify(r[0]));return r[1]}
async function resetProgress(){const b=$('tf113ConfirmReset');if(b)b.disabled=true;let changed=0;try{const keys=[];for(let i=0;i<localStorage.length;i++)keys.push(localStorage.key(i));for(const k of keys){if(!k||!k.startsWith('taskflow_')||k===CFG||k===META||k.includes('firebase')||k.includes('profile_photo')||k.includes('503020')||k.includes('share_')||k.includes('cloud_sync_meta')||k.includes('cloud_bound'))continue;changed+=processKey(k)}const main=get(MAIN);if(main){set(BACK,main);set(REC,main)}set(TOUCH,String(Date.now()));if(window.TaskFlowCloudSync&&typeof window.TaskFlowCloudSync.syncNow==='function'){try{await window.TaskFlowCloudSync.syncNow()}catch(_){}}closeReset();const m=$('tfProfileMessage');if(m){m.textContent=changed?'Sistema reiniciado a 0 días. Tus hábitos y tareas se conservaron.':'Los contadores ya estaban en 0. Tus hábitos y tareas no fueron modificados.';m.className='tf-profile-message ok'}setTimeout(()=>location.reload(),700)}finally{if(b)b.disabled=false}}

function markCloud(){set(META,String(Date.now()));if(cloudTimer)clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>{cloudTimer=0;pushCloud().catch(()=>{})},800)}
async function token(force){return window.TaskFlowFirebase&&window.TaskFlowFirebase.getIdToken?window.TaskFlowFirebase.getIdToken(!!force):null}
async function req(uid,opt){let t=await token(false);if(!t)throw new Error('AUTH');const url=API+'/users/'+encodeURIComponent(uid)+'/settings/routinesV113';const o=Object.assign({},opt||{});o.headers=Object.assign({'Authorization':'Bearer '+t,'Content-Type':'application/json'},o.headers||{});let r=await fetch(url,o);if(r.status===401){t=await token(true);if(t){o.headers.Authorization='Bearer '+t;r=await fetch(url,o)}}if(r.status===404)return null;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('HTTP '+r.status);return d}
async function pushCloud(){if(cloudBusy||!cloudUid)return;cloudBusy=true;try{const at=Number(get(META))||Date.now();await req(cloudUid,{method:'PATCH',body:JSON.stringify({fields:{config:{stringValue:get(CFG)||''},updatedAt:{integerValue:String(at)}}})})}finally{cloudBusy=false}}
async function reconcile(uid){const local=Number(get(META))||0,d=await req(uid,{method:'GET'});if(!d){if(!local)set(META,String(Date.now()));await pushCloud();return}const f=d.fields||{},remote=Number(f.updatedAt&&f.updatedAt.integerValue||0),data=String(f.config&&f.config.stringValue||'');if(remote>local&&data){set(CFG,data);set(META,String(remote));apply();renderManager()}else if(local>remote)await pushCloud()}
function cloudWatch(){const u=window.TaskFlowFirebase&&window.TaskFlowFirebase.getUser?window.TaskFlowFirebase.getUser():null,uid=u&&u.uid||'';if(uid===cloudUid)return;cloudUid=uid;if(uid)reconcile(uid).catch(()=>{})}
function refresh(){refreshTimer=0;mountReset();apply();cloudWatch()}
function schedule(){if(!refreshTimer)refreshTimer=setTimeout(refresh,150)}
function start(){style();cfg();manager();resetModal();document.addEventListener('input',search,true);document.addEventListener('change',search,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeManager();closeReset()}},true);refresh();setTimeout(refresh,500);setTimeout(refresh,1500);new MutationObserver(ms=>{if(ms.some(m=>m.addedNodes&&m.addedNodes.length))schedule()}).observe(document.body,{subtree:true,childList:true});setInterval(cloudWatch,1800)}
window.TaskFlowV113={openRoutineManager:openManager,openSystemReset:openReset,refresh};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();